maps =[
        [
        ['sky','sky','sky','sky','sky','sky','sky'],
        ['sky','sky','sky','sky','sky','sky','door'],
        ['sky','sky','sky','sky','sky','sky','floor'],
        ['sky','sky','sky','sky','floor','floor','sky'],
        ['sky','sky','floor','floor','sky','sky','sky'],
        ['start','sky','sky','sky','sky','sky','sky'],
        ['floor','floor','floor','floor','floor','floor','floor']
        ],
        [
        ['sky','sky','sky','sky','sky','sky','door'],
        ['sky','sky','sky','sky','sky','floor','floor'],
        ['sky','sky','sky','sky','floor','sky','sky'],
        ['sky','sky','sky','floor','sky','sky','sky'],
        ['sky','sky','floor','sky','sky','sky','sky'],
        ['start','sky','sky','sky','sky','sky','sky'],
        ['floor','floor','floor','floor','sky','sky','sky']
        ],
        [
        ['sky','sky','sky','door','sky','sky','sky'],
        ['sky','floor','sky','floor','floor', 'sky','sky'],
        ['sky','sky','sky','sky','sky','sky','sky'],
        ['floor','floor','floor','floor','floor','floor','floor'],
        ['sky','sky','void','sky','sky','sky','sky'],
        ['start','sky','sky','void','sky','sky','sky'],
        ['floor','floor','floor','floor','sky','floor','floor']
        ],
        [
        ['sky','sky','sky','sky','sky','sky','door','sky','sky','sky'],
        ['sky','sky','sky','sky','sky','sky','floor','floor','sky','sky'],
        ['sky','sky','sky','sky','sky','sky','sky','sky','floor','sky'],
        ['sky','sky','sky','sky','sky','sky','sky','sky','sky','floor'],
        ['sky','sky','sky','sky','sky','sky','sky','sky','sky','sky'],
        ['sky','sky','sky','sky','floor','floor','sky','sky','sky','sky'],
        ['sky','sky','sky','floor','sky','sky','sky','sky','sky','floor'],
        ['sky','sky','floor','sky','sky','floor','floor','sky','sky','sky'],
        ['start','sky','sky','sky','sky','sky','sky','sky','sky','sky'],
        ['floor','floor','floor','floor','sky','sky','sky','floor','floor','floor']
        ]
    ]